# -*- coding: utf-8 -*-
"""CNN-NO DISTORTION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GptWlX7HCr7fkxqjpcrsS37xKt9P4w9N
"""

import tensorflow as tf
import numpy as np
import pandas as pd
from pathlib import Path
import os.path
import matplotlib.pyplot as plt
from IPython.display import Image, display, Markdown
import matplotlib.cm as cm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from time import perf_counter
import seaborn as sns
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.models import Sequential

from google.colab import drive
drive.mount('/content/drive')

image_dir = Path('/content/drive/MyDrive/01/train')

# Get filepaths and labels
filepaths = list(image_dir.glob(r'**/*.png'))
labels = list(map(lambda x: os.path.split(os.path.split(x)[0])[1], filepaths))

filepaths = pd.Series(filepaths, name='Filepath').astype(str)
labels = pd.Series(labels, name='Label')

# Concatenate filepaths and labels
image_df = pd.concat([filepaths, labels], axis=1)

# Shuffle the DataFrame and reset index
image_df = image_df.sample(frac=1).reset_index(drop = True)

# Show the result
image_df.head(3)

# Display some pictures of the dataset with their labels
fig, axes = plt.subplots(nrows=3, ncols=4, figsize=(10, 7),
                        subplot_kw={'xticks': [], 'yticks': []})

for i, ax in enumerate(axes.flat):
    ax.imshow(plt.imread(image_df.Filepath[i]))
    ax.set_title(image_df.Label[i])
plt.tight_layout()
plt.show()

# Display the number of pictures of each category
vc = image_df['Label'].value_counts()
plt.figure(figsize=(9,5))
sns.barplot(x = vc.index, y = vc, palette = "rocket")
plt.title("Number of pictures of each category", fontsize = 15)
plt.show()

# Define the data augmentation parameters and create the image data generator
datagen = ImageDataGenerator(rescale=1./255,
                             rotation_range=20,
                             width_shift_range=0.2,
                             height_shift_range=0.2,
                             shear_range=0.2,
                             zoom_range=0.2,
                             horizontal_flip=True,
                             validation_split=0.2)

train_generator = datagen.flow_from_directory("/content/drive/MyDrive/01/train",
                                              target_size=(224, 224),
                                              batch_size=64,
                                              class_mode="binary",
                                              subset="training")

test_generator = datagen.flow_from_directory("/content/drive/MyDrive/01/train",
                                             target_size=(224, 224),
                                             batch_size=64,
                                             class_mode="binary",
                                             subset="validation")

# Separate in train and test data
train_df, test_df = train_test_split(image_df, train_size=0.9, shuffle=True, random_state=1)

# Define the model architecture
model = Sequential([
    Conv2D(32, (3, 3), activation="relu", input_shape=(224, 224, 3)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation="relu"),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation="relu"),
    MaxPooling2D((2, 2)),
    Conv2D(256, (3, 3), activation="relu"),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(256, activation="relu"),
    Dropout(0.5),
    Dense(1, activation="sigmoid")
])

# Compile the model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Train the model
import time

start_time = time.time()

history = model.fit(train_generator, epochs=5, validation_data=test_generator)

end_time = time.time()
elapsed_time = end_time - start_time
print("Elapsed time: ", elapsed_time, "seconds")

# Save the trained model
model.save('my_trained_cnn_model.h5')



# Evaluate the model
test_loss, test_acc = model.evaluate(test_generator)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_acc)

from keras.callbacks import ModelCheckpoint
from sklearn.metrics import classification_report


# Evaluate the model on the test set
scores = model.evaluate(test_generator, verbose=0)
print("Test loss:", scores[0])
print("Test accuracy:", scores[1])

# Make predictions on the test set
y_true = test_generator.classes
y_pred = model.predict(test_generator)
y_pred = y_pred > 0.5

# Print classification report and confusion matrix
print("Classification Report:")
print(classification_report(y_true, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_true, y_pred))

pd.DataFrame(history.history)[['accuracy','val_accuracy']].plot()
plt.title("Accuracy")
plt.show()

pd.DataFrame(history.history)[['loss','val_loss']].plot()
plt.title("Loss")
plt.show()

import psutil

# Get the system memory usage
mem = psutil.virtual_memory()

# Print the memory usage in GB
print(f"Total memory: {mem.total/1e9:.2f} GB")
print(f"Available memory: {mem.available/1e9:.2f} GB")
print(f"Used memory: {mem.used/1e9:.2f} GB")

"""Submission

"""

#Create test generator

test_dir = '/content/drive/MyDrive/01/test/test_images'
test_csv = '/content/drive/MyDrive/01/test/test.csv'
test_df = pd.read_csv(test_csv)
test_df['id_code'] = test_df['id_code'] + ".png"
test_df['diagnosis'] = np.zeros(test_df.shape[0])
img_size = (224, 224)
ts_length = len(test_df)
test_batch_size = max(sorted([ts_length // n for n in range(1, ts_length + 1) if ts_length%n == 0 and ts_length/n <= 80]))

def scalar(img):
    return img
    
tst_gen = ImageDataGenerator(preprocessing_function= scalar)
test_gen = tst_gen.flow_from_dataframe( test_df, x_col= 'id_code', y_col= 'diagnosis', directory= test_dir, target_size= img_size,
                                        color_mode= 'rgb', class_mode='raw', shuffle= False, batch_size= test_batch_size)

#Get Prediction

preds = model.predict_generator(test_gen)
y_pred = np.argmax(preds, axis=1)
y_pred

test_df['diagnosis'] = y_pred
test_df

test_data = pd.read_csv("/content/drive/MyDrive/dataset/test.csv")
test_data["filename"] = test_data["id_code"].map(lambda x:x+".png")
test_data.head()

test_df.to_csv('Submission.csv')