# -*- coding: utf-8 -*-
"""RESNET50.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuF1uodCh_96lg61iBuftaGbp5iOKcji
"""

import numpy as np
import pandas as pd
from pathlib import Path
import os.path
import matplotlib.pyplot as plt
from IPython.display import Image, display, Markdown
import matplotlib.cm as cm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from time import perf_counter
import seaborn as sns
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.resnet50 import ResNet50


def printmd(string):
    # Print with Markdowns    
    display(Markdown(string))

from google.colab import drive
drive.mount('/content/drive')

image_dir = Path('/content/drive/MyDrive/01/train')

# Get filepaths and labels
filepaths = list(image_dir.glob(r'**/*.png'))
labels = list(map(lambda x: os.path.split(os.path.split(x)[0])[1], filepaths))

filepaths = pd.Series(filepaths, name='Filepath').astype(str)
labels = pd.Series(labels, name='Label')

# Concatenate filepaths and labels
image_df = pd.concat([filepaths, labels], axis=1)

# Shuffle the DataFrame and reset index
image_df = image_df.sample(frac=1).reset_index(drop = True)

# Show the result
image_df.head(3)

"""# Visualization"""

# Display some pictures of the dataset with their labels
fig, axes = plt.subplots(nrows=3, ncols=4, figsize=(10, 7),
                        subplot_kw={'xticks': [], 'yticks': []})

for i, ax in enumerate(axes.flat):
    ax.imshow(plt.imread(image_df.Filepath[i]))
    ax.set_title(image_df.Label[i])
plt.tight_layout()
plt.show()

def preprocess_image(image_path, desired_size=300):
    im = cv2.imread(image_path)
    im = cv2.cvtColor(im,cv2.COLOR_BGR2RGB)
    im = cv2.resize(im, (desired_size, desired_size))
    im = cv2.addWeighted(im, 4, cv2.blur(im, ksize=(10,10)), -4, 128)
    return im

# Display the number of pictures of each category
vc = image_df['Label'].value_counts()
plt.figure(figsize=(9,5))
sns.barplot(x = vc.index, y = vc, palette = "rocket")
plt.title("Number of pictures of each category", fontsize = 15)
plt.show()

"""# Load the Images with a generator<a class="anchor" id="2"></a>"""

def create_gen():
    # Load the Images with a generator and Data Augmentation
    train_generator = tf.keras.preprocessing.image.ImageDataGenerator(
        preprocessing_function=tf.keras.applications.mobilenet_v2.preprocess_input,
        validation_split=0.2
    )

    test_generator = tf.keras.preprocessing.image.ImageDataGenerator(
        preprocessing_function=tf.keras.applications.mobilenet_v2.preprocess_input
    )

    train_images = train_generator.flow_from_dataframe(
        dataframe=train_df,
        x_col='Filepath',
        y_col='Label',
        target_size=(224, 224),
        color_mode='rgb',
        class_mode='categorical',
        batch_size=64,
        shuffle=True,
        seed=0,
        subset='training',
        rotation_range=30, # Uncomment to use data augmentation
        zoom_range=0.15,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.15,
        horizontal_flip=True,
        fill_mode="nearest"
    )

    val_images = train_generator.flow_from_dataframe(
        dataframe=train_df,
        x_col='Filepath',
        y_col='Label',
        target_size=(224, 224),
        color_mode='rgb',
        class_mode='categorical',
        batch_size=64,
        shuffle=True,
        seed=0,
        subset='validation',
        rotation_range=30, # Uncomment to use data augmentation
        zoom_range=0.15,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.15,
        horizontal_flip=True,
        fill_mode="nearest"
    )

    test_images = test_generator.flow_from_dataframe(
        dataframe=test_df,
        x_col='Filepath',
        y_col='Label',
        target_size=(224, 224),
        color_mode='rgb',
        class_mode='categorical',
        batch_size=64,
        shuffle=False
    )
    
    return train_generator,test_generator,train_images,val_images,test_images

# Separate in train and test data
train_df, test_df = train_test_split(image_df, train_size=0.7, shuffle=True, random_state=1)

"""# resnet50<a class="anchor" id="4"></a>"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers.legacy import Adam

# Define the ResNet50 model
resnet50_model = keras.applications.ResNet50(
    include_top=False,
    weights='imagenet',
    input_shape=(224, 224, 3)
)

# Set the ResNet50 model to be non-trainable
resnet50_model.trainable = False

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from tensorflow.keras import models, layers, optimizers

# Create the generators
train_generator, test_generator, train_images, val_images, test_images = create_gen()

# Load the pretained model
resnet50_model = ResNet50(
    include_top=False,
    weights='imagenet',
    input_shape=(224, 224, 3)
)

# Freeze the layers up to a specific layer
for layer in resnet50_model.layers[:100]:
    layer.trainable = False

# Add a new output layer
x = resnet50_model.output
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(256, activation='relu')(x)
predictions = layers.Dense(2, activation='sigmoid')(x)

# Define the full model
model = models.Model(inputs=resnet50_model.input, outputs=predictions)


# Save the entire model as a `.keras` zip archive.
model.save('my_model.keras')
# Fine-tune the model
model.compile(
    optimizer=optimizers.Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy', 'AUC']
)


# define the callbacks
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=0.0001)
early_stop = EarlyStopping(monitor='val_loss', patience=5)

history = model.fit(
    train_images,
    epochs=10,
    validation_data=val_images,
    callbacks=[reduce_lr, early_stop]
)

# Save the entire model as a `.keras` zip archive.
model.save('my_model.keras')

# Reload a fresh Keras model from the `.keras` zip archive:

new_model = tf.keras.models.load_model('my_model.keras')

# Show the model architecture
new_model.summary()

#Try running evaluate and predict with the loaded model: 
#loss, acc = new_model.evaluate(test_images, test_labels, verbose=2)
#print('Restored model, accuracy: {:5.2f}%'.format(100 * acc))

#print(new_model.predict(test_images).shape)

pd.DataFrame(history.history)[['accuracy','val_accuracy']].plot()
plt.title("Accuracy")
plt.show()

pd.DataFrame(history.history)[['loss','val_loss']].plot()
plt.title("Loss")
plt.show()

pd.DataFrame(history.history)[['accuracy','val_accuracy']].plot()
plt.title("Accuracy")
plt.show()

pd.DataFrame(history.history)[['loss','val_loss']].plot()
plt.title("Loss")
plt.show()

results = model.evaluate(test_images, verbose=0)

printmd(" ## Test Loss: {:.5f}".format(results[0]))
printmd("## Accuracy on the test set: {:.2f}%".format(results[1] * 100))
print('\n')

# Predict the label of the test_images
pred = model.predict(test_images)
pred = np.argmax(pred,axis=1)

# Map the label
labels = (train_images.class_indices)
labels = dict((v,k) for k,v in labels.items())
pred = [labels[k] for k in pred]

from sklearn.metrics import classification_report
y_test = list(test_df.Label)
from sklearn import metrics
print('Accuracy:', np.round(metrics.accuracy_score(y_test,pred),5))
print('Precision:', np.round(metrics.precision_score(y_test,pred, average='weighted'),2))
print('Recall:', np.round(metrics.recall_score(y_test,pred, average='weighted'),2))
print('F1 Score:', np.round(metrics.f1_score(y_test,pred, average='weighted'),2))
print('Cohen Kappa Score:', np.round(metrics.cohen_kappa_score(y_test,pred),2))
print(classification_report(y_test, pred))

cf_matrix = confusion_matrix(y_test, pred, normalize='true')
plt.figure(figsize = (10,6))
sns.heatmap(cf_matrix, annot=True, xticklabels = sorted(set(y_test)), yticklabels = sorted(set(y_test)))
plt.title('Normalized Confusion Matrix')
plt.show()

import psutil

# Get the system memory usage
mem = psutil.virtual_memory()

# Print the memory usage in GB
print(f"Total memory: {mem.total/1e9:.2f} GB")
print(f"Available memory: {mem.available/1e9:.2f} GB")
print(f"Used memory: {mem.used/1e9:.2f} GB")

test_data = pd.read_csv("/content/drive/MyDrive/dataset/test.csv")
test_data["filename"] = test_data["id_code"].map(lambda x:x+".png")
test_data.head()

filenames=test_generator.filenames
results=pd.DataFrame({"id_code":filenames,
                      "diagnosis":np.argmax(predictions,axis=1)})
results['id_code'] = results['id_code'].map(lambda x: str(x)[:-4])
results.to_csv("submission.csv",index=False)

test_dir = '/content/drive/MyDrive/01/test/test_images'
test_csv = '/content/drive/MyDrive/01/test/test.csv'
test_df = pd.read_csv(test_csv)
test_df['id_code'] = test_df['id_code'] + ".png"
test_df['diagnosis'] = np.zeros(test_df.shape[0])
img_size = (224, 224)
ts_length = len(test_df)
test_batch_size = max(sorted([ts_length // n for n in range(1, ts_length + 1) if ts_length%n == 0 and ts_length/n <= 80]))

def scalar(img):
    return img
    
tst_gen = ImageDataGenerator(preprocessing_function= scalar)
test_gen = tst_gen.flow_from_dataframe( test_df, x_col= 'id_code', y_col= 'diagnosis', directory= test_dir, target_size= img_size,
                                        color_mode= 'rgb', class_mode='raw', shuffle= False, batch_size= test_batch_size)

#Get Prediction

preds = model.predict(test_gen)
y_pred = np.argmax(preds, axis=1)
y_pred

test_df['diagnosis'] = y_pred
test_df

import cv2
from google.colab.patches import cv2_imshow

img = cv2.imread("/content/drive/MyDrive/01/test/test_images/0005cfc8afb6.png", cv2.IMREAD_COLOR)

cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

test_df.to_csv('./submission.csv', index=False)